<?php

use App\RadiologyTypeCategory;
use Illuminate\Database\Seeder;

class RadiologyTypeCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $mri = RadiologyTypeCategory::create(['ar_name'=>'الرنين المغناطيسى المغلق 1.5 تسلا','en_name'=>'Closed MRI 1.5 Tesla']);
        $mri->radiology_types()->create(['ar_name'=>'المخ','en_name'=>'Brain']);
        $mri->radiology_types()->create(['ar_name'=>'شرايين المخ','en_name'=>'MRA']);
        $mri->radiology_types()->create(['ar_name'=>'أوردة المخ بالصبغه','en_name'=>'MRV']);
        $mri->radiology_types()->create(['ar_name'=>'المخ و شرايين المخ','en_name'=>'Brain & MRA']);
        $mri->radiology_types()->create(['ar_name'=>'المخ و أوردة المخ بالصبغه','en_name'=>'Brain & MRV']);
        $mri->radiology_types()->create(['ar_name'=>'شرايين و أوردة المخ بالصبغه','en_name'=>'MRA & MRV']);
        $mri->radiology_types()->create(['ar_name'=>'المخ وشرايين المخ واوردة المخ بالصبغه','en_name'=>'Brain & MRA & V']);
        $mri->radiology_types()->create(['ar_name'=>'العمود الفقرى بالكامل','en_name'=>'Whole Spine ']);
        $mri->radiology_types()->create(['ar_name'=>'الغدة النخامية ( بالصبغة )','en_name'=>'Sella Turcica']);
        $mri->radiology_types()->create(['ar_name'=>'العين ( بالصبغة )','en_name'=>'Orbits']);
        $mri->radiology_types()->create(['ar_name'=>'الأذن ( بالصبغة )','en_name'=>'Petrous Bone ( CPA )']);
        $mri->radiology_types()->create(['ar_name'=>'مفصلى الفك','en_name'=>'Temporomandibular Joints ( TMJ )']);
        $mri->radiology_types()->create(['ar_name'=>'الجيوب الأنفية ( بالصبغة )','en_name'=>'Paranasal Sinuses']);
        $mri->radiology_types()->create(['ar_name'=>'العنق و الحنجرة ( بالصبغة )','en_name'=>'Neck & Larynx']);
        $mri->radiology_types()->create(['ar_name'=>'البلعوم الأنفى بالصبغه','en_name'=>'Naso Pharynx']);
        $mri->radiology_types()->create(['ar_name'=>'اللسان','en_name'=>'Tongue']);
        $mri->radiology_types()->create(['ar_name'=>'الفقرات العنقية','en_name'=>'Cervical Spine ( CS )']);
        $mri->radiology_types()->create(['ar_name'=>'الفقرات الظهرية','en_name'=>'Dorsal Spine ( DS )']);
        $mri->radiology_types()->create(['ar_name'=>'الفقرات القطنية الظهرية','en_name'=>'Dorsolumbar']);
        $mri->radiology_types()->create(['ar_name'=>'الفقرات القطنية','en_name'=>'Lumbar Spine ( L.S.S )']);
        $mri->radiology_types()->create(['ar_name'=>'الكتف','en_name'=>'Shoulder']);
        $mri->radiology_types()->create(['ar_name'=>'مفصلى الحوض','en_name'=>'Both Hips']);
        $mri->radiology_types()->create(['ar_name'=>'الكاحل','en_name'=>'Ankle']);
        $mri->radiology_types()->create(['ar_name'=>'السمانة','en_name'=>'Calf']);
        $mri->radiology_types()->create(['ar_name'=>'القدم','en_name'=>'Foot']);
        $mri->radiology_types()->create(['ar_name'=>'أصابع اليد','en_name'=>'Fingers']);
        $mri->radiology_types()->create(['ar_name'=>'أصابع القدم','en_name'=>'Toes']);
        $mri->radiology_types()->create(['ar_name'=>'الساق','en_name'=>'Leg']);
        $mri->radiology_types()->create(['ar_name'=>'عظمة الفخذ','en_name'=>'Femur']);
        $mri->radiology_types()->create(['ar_name'=>'الفخذ','en_name'=>'Thigh']);
        $mri->radiology_types()->create(['ar_name'=>'اليد','en_name'=>'Hand']);
        $mri->radiology_types()->create(['ar_name'=>'الرسغ','en_name'=>'Wrist']);
        $mri->radiology_types()->create(['ar_name'=>'الكوع','en_name'=>'Elbow']);
        $mri->radiology_types()->create(['ar_name'=>'الساعد','en_name'=>'Arm Or Forearm']);
        $mri->radiology_types()->create(['ar_name'=>'العضد','en_name'=>'Humerus']);
        $mri->radiology_types()->create(['ar_name'=>'الحوض ( عظام )','en_name'=>'Pelvis ( Bone ) - Both Hips']);
        $mri->radiology_types()->create(['ar_name'=>'القلب ','en_name'=>'Heart']);
        $mri->radiology_types()->create(['ar_name'=>'الاطراف السفلية','en_name'=>'Angio Lower Limbs']);
        $mri->radiology_types()->create(['ar_name'=>'شرايين الرقبة','en_name'=>'Angio Carotid']);
        $mri->radiology_types()->create(['ar_name'=>'شرايين الكلى','en_name'=>'Angio Renal']);
        $mri->radiology_types()->create(['ar_name'=>'الشريان الرئوى ','en_name'=>'Angio Palmonary']);
        $mri->radiology_types()->create(['ar_name'=>'الطيف المخى','en_name'=>'Spectroscopy']);
        $mri->radiology_types()->create(['ar_name'=>'التصوير بالرنين المغناطيسي الانتشاري للالياف العصبيه','en_name'=>'Tractography']);
        $mri->radiology_types()->create(['ar_name'=>'القنوات المرارية','en_name'=>'MRCP']);
        $mri->radiology_types()->create(['ar_name'=>'المسالك البولية','en_name'=>'MRU']);
        $mri->radiology_types()->create(['ar_name'=>'البنكرياس','en_name'=>'Pancreas']);
        $mri->radiology_types()->create(['ar_name'=>'الكلى','en_name'=>'Kidneys']);
        $mri->radiology_types()->create(['ar_name'=>'الكبد','en_name'=>'Triphasic Liver']);
        $mri->radiology_types()->create(['ar_name'=>'الامعاء الدقيقة','en_name'=>'Entrography']);
        $mri->radiology_types()->create(['ar_name'=>'الثدى','en_name'=>'Mammography']);
        $mri->radiology_types()->create(['ar_name'=>'تدفق سائل النخاع الشوكي','en_name'=>'Brain CSF Flow']);
        $mri->radiology_types()->create(['ar_name'=>'نضح الدم بالمخ','en_name'=>'Perfusion']);
        $mri->radiology_types()->create(['ar_name'=>'نضح الدم بالمخ و المسح الطيفي','en_name'=>'Perfusion & Spectroscopy']);
        $mri->radiology_types()->create(['ar_name'=>'المسح الطيفي و المخ','en_name'=>'Brain & Spectroscopy']);
        $mri->radiology_types()->create(['ar_name'=>'نضح الدم ','en_name'=>'Perfusion &Tractography']);
        $mri->radiology_types()->create(['ar_name'=>'التصوير بالرنين المغناطيسي الانتشاري للالياف العصيبه و المخ','en_name'=>'Brain &Tractography']);
        $mri->radiology_types()->create(['ar_name'=>'التصوير بالرنين المغناطيسي الانتشاري للالياف العصيبه و المسح الطيفي','en_name'=>'Tractography & Spectroscopy']);
        $mri->radiology_types()->create(['ar_name'=>'فحص الحوض الديناميكي بالصبغه','en_name'=>'Dynamic Pelvis']);
        $mri->radiology_types()->create(['ar_name'=>'حزمه فحص السكته الدماغية','en_name'=>'Stroke Package']);
        $mri->radiology_types()->create(['ar_name'=>'فحص الضفيرة العضدية','en_name'=>'Brachil Plexus']);
        $mri->radiology_types()->create(['ar_name'=>'فحص تقاطع العنق مع الجمجمة','en_name'=>'Cranio c-s']);
        $mri->radiology_types()->create(['ar_name'=>'البروستاتا','en_name'=>'Prostate']);
        $mri->radiology_types()->create(['ar_name'=>'فحص المستقيم','en_name'=>'Rectum']);
        $mri->radiology_types()->create(['ar_name'=>'وعاء الخصيتين','en_name'=>'Scrotum']);
        $mri->radiology_types()->create(['ar_name'=>'فحص الكليتين','en_name'=>'Renogram']);
        $mri->radiology_types()->create(['ar_name'=>'جدار الصدر','en_name'=>'Chest Wall']);
        $mri->radiology_types()->create(['ar_name'=>'الحوض','en_name'=>'Pelvis']);
        $mri->radiology_types()->create(['ar_name'=>'ناصور','en_name'=>'Fistula']);
        $mri->radiology_types()->create(['ar_name'=>'العظم الكتفي','en_name'=>'Scapula']);
        $mri->radiology_types()->create(['ar_name'=>'فحص مفصل العجزي الحرقفي','en_name'=>'Sacroilic']);
        $mri->radiology_types()->create(['ar_name'=>'عظم العضد','en_name'=>'Humerus']);
        $mri->radiology_types()->create(['ar_name'=>'عظمة العجز','en_name'=>'Sacrum']);
        $mri->radiology_types()->create(['ar_name'=>'فحص مفصل الكتف بالصبغة ','en_name'=>'Shoulder Arthrogram']);
        $mri->radiology_types()->create(['ar_name'=>'فحص مفصل الرسغ بالصبغة','en_name'=>'Wrist Arthrogram']);
        $mri->radiology_types()->create(['ar_name'=>'التصوير العصبي الكمي','en_name'=>'neuro Quant']);
        $mri->radiology_types()->create(['ar_name'=>'سيلان سائل النخاع الشوكي من الانف','en_name'=>'CSF Rhinorrhea']);
        $mri->radiology_types()->create(['ar_name'=>'زرع قوقعة بالاذن','en_name'=>'Cochlear Implant']);
        $mri->radiology_types()->create(['ar_name'=>' فخص الورم الكوليسترولي بالاذن','en_name'=>'Cholesteatoma']);
        $mri->radiology_types()->create(['ar_name'=>'صبغه الجادولينيام','en_name'=>'Contrast Medium ( Gadolinum )']);
        $mri->radiology_types()->create(['ar_name'=>'مهدىء عام رنين مغناطيسى','en_name'=>'']);
        //////////////////////////////////////////////////////////////////////////////////////////
        $mri = RadiologyTypeCategory::create(['ar_name'=>'فحوصات','en_name'=>'MRI Open']);
        $mri->radiology_types()->create(['ar_name'=>'المخ','en_name'=>'Brain']);
        $mri->radiology_types()->create(['ar_name'=>'شرايين المخ','en_name'=>'MRA']);
        $mri->radiology_types()->create(['ar_name'=>'أوردة المخ','en_name'=>'MRV ']);
        $mri->radiology_types()->create(['ar_name'=>'المخ و شرايين المخ','en_name'=>'Brain & MRA ']);
        $mri->radiology_types()->create(['ar_name'=>'المخ و أوردة المخ بالصبغه','en_name'=>'Brain&MRV ']);
        $mri->radiology_types()->create(['ar_name'=>'شرايين و أوردة المخ بالصبغه','en_name'=>'MRA&MRV']);
        $mri->radiology_types()->create(['ar_name'=>'المخ وشرايين المخ واوردة المخ','en_name'=>'Brain & MRA & V']);
        $mri->radiology_types()->create(['ar_name'=>'العمود الفقرى بالكامل','en_name'=>'Whole Spine']);
        $mri->radiology_types()->create(['ar_name'=>'الغدة النخامية ','en_name'=>'Sella trucica']);
        $mri->radiology_types()->create(['ar_name'=>'العين ','en_name'=>'Orbits']);
        $mri->radiology_types()->create(['ar_name'=>'الفقرات العنقية','en_name'=>'Cervical Spine']);
        $mri->radiology_types()->create(['ar_name'=>'الفقرات القطنية','en_name'=>'Lumbar Spine']);
        $mri->radiology_types()->create(['ar_name'=>'مفصلى الحوض','en_name'=>'Both Hips']);
        $mri->radiology_types()->create(['ar_name'=>'الركبة','en_name'=>'Knee ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'الكتف','en_name'=>'Shoulder ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'الكاحل','en_name'=>'Ankle ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'الساق او السمانة','en_name'=>'Leg Or Calf ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'القدم او اصبع القدم','en_name'=>'foot Or Toes ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'الفخذ ','en_name'=>'Thigh Or Femur ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'الكوع','en_name'=>'Elbow ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'الساعد','en_name'=>'Forarm ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'الرسغ','en_name'=>'Wrist ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'اليد او اصبع اليد','en_name'=>'Hand Or Fingers ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'استكمال مرحلة واحدة','en_name'=>'فحص اضافي T2 ']);
        $mri->radiology_types()->create(['ar_name'=>'استخدام صبغة فى الفحص','en_name'=>'contrast mri']);
        $mri->radiology_types()->create(['ar_name'=>'مهدىء عام رنين مغناطيسى ','en_name'=>' ']);
        //////////////////////////////////////////////////////////////////////////////////////////
        $mri = RadiologyTypeCategory::create(['ar_name'=>'الاشعة المقطعية متعددة المقاطع','en_name'=>'Multi Slice CT']);
        $mri->radiology_types()->create(['ar_name'=>'المخ بدون صبغة ','en_name'=>'Brain non contrast']);
        $mri->radiology_types()->create(['ar_name'=>'المخ بالصبغة ','en_name'=>'Brain with contrast']);
        $mri->radiology_types()->create(['ar_name'=>'الغدة النخامية','en_name'=>'Sella Turcica']);
        $mri->radiology_types()->create(['ar_name'=>'العين','en_name'=>'Orbits']);
        $mri->radiology_types()->create(['ar_name'=>'البلعوم الأنفى','en_name'=>'Naso - Pharynx']);
        $mri->radiology_types()->create(['ar_name'=>'ثنائية المراحل على الرقبة','en_name'=>'2 Phase Neck']);
        $mri->radiology_types()->create(['ar_name'=>'الجيوب الأنفية بالكامل','en_name'=>'Paranasal Sinuses ( Axial and Coronal )']);
        $mri->radiology_types()->create(['ar_name'=>'الجيوب الأنفية بالكامل وبالصبغة','en_name'=>'Paranasal Sinuses ( Axial and Coronal with contrast)']);
        $mri->radiology_types()->create(['ar_name'=>'الجيوب الأنفية -  مقاطع','en_name'=>'Paranasal Sinuses ( Coronal Only )']);
        $mri->radiology_types()->create(['ar_name'=>'العظمة الصخرية مقاطع أفقية ورأسية ','en_name'=>'Petrous Bone ( Axial and Coronal )']);
        $mri->radiology_types()->create(['ar_name'=>'مفصلى الفك','en_name'=>'Temporomandibular Joints ( TMJ )']);
        $mri->radiology_types()->create(['ar_name'=>'الفقرات القطنية والعجزية بالكامل','en_name'=>'Lumbosacral Spine ( L1 -S1 )']);
        $mri->radiology_types()->create(['ar_name'=>'فقرات عنقية بدون صبغة','en_name'=>'Cervical Spine ( Non Contrast )']);
        $mri->radiology_types()->create(['ar_name'=>'فقرات ظهرية - 6 فقرات فقط بدون صبغة','en_name'=>'Dorsal Spine (6 only )']);
        $mri->radiology_types()->create(['ar_name'=>'الصدر','en_name'=>'Chest']);
        $mri->radiology_types()->create(['ar_name'=>'الصدر (بدون صبغة)','en_name'=>'Chest ( Non Contrast )']);
        $mri->radiology_types()->create(['ar_name'=>'مقطعية على البطن فائقة الدقة( بدون صبغة)','en_name'=>'Non contrast Abdomen thin cuts']);
        $mri->radiology_types()->create(['ar_name'=>'البطن والحوض','en_name'=>'Abdomen & Pelvis']);
        $mri->radiology_types()->create(['ar_name'=>'البطن و الحوض ثلاثية المراحل (الكبد)','en_name'=>'Abdomen& triphasic']);
        $mri->radiology_types()->create(['ar_name'=>'ثلاثية المراحل على البطن(البنكرياس)','en_name'=>'Abdomen& triphasic(pancreas)']);
        $mri->radiology_types()->create(['ar_name'=>' ثلاثية المراحل على الكبد مع قياس حجم الكبد','en_name'=>'Triphasic liver with volume']);
        $mri->radiology_types()->create(['ar_name'=>' ثلاثية المراحل على الكبد مع الامعاء الدقيقة و الغليظة','en_name'=>'Triphasic liver with entrocolonography']);
        $mri->radiology_types()->create(['ar_name'=>'البطن و الحوض و النزيف الداخلى','en_name'=>'GI Bleeding']);
        $mri->radiology_types()->create(['ar_name'=>'البطن والحوض و الناصور ','en_name'=>'CT Sinogram']);
        $mri->radiology_types()->create(['ar_name'=>'ثنائية المراحل على البطن(الغدة فوق الكلوية)','en_name'=>'2 Phase Abdomen (Adrenal)']);
        $mri->radiology_types()->create(['ar_name'=>'فحص  للمسالك البولية بالصبغة','en_name'=>'CTA Urography Haematurie']);
        $mri->radiology_types()->create(['ar_name'=>'فحص على القولون','en_name'=>'CT Colonography']);
        $mri->radiology_types()->create(['ar_name'=>'فحص على الامعاء الدقيقة','en_name'=>'CT Enterography']);
        $mri->radiology_types()->create(['ar_name'=>'متعددة المقاطع على الكلى ','en_name'=>'Multi Phase Kidney']);
        $mri->radiology_types()->create(['ar_name'=>'قياس طول الاطراف ','en_name'=>'Scanogram']);
        $mri->radiology_types()->create(['ar_name'=>'مفصلى الحوض','en_name'=>'Both Hips']);
        $mri->radiology_types()->create(['ar_name'=>'ركبة','en_name'=>'Knee ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'مفصل الكاحل','en_name'=>'Ankle']);
        $mri->radiology_types()->create(['ar_name'=>'الكتف','en_name'=>'Shoulder ( One Side )']);
        $mri->radiology_types()->create(['ar_name'=>'عظام الأطراف','en_name'=>'Limbs']);
        $mri->radiology_types()->create(['ar_name'=>'فحص ثلاثى الابعاد على الوجه(بدون صبغة)','en_name'=>'3D face( Non Contrast )']);
        $mri->radiology_types()->create(['ar_name'=>'فحص انجيو على شرايين الوجهة(بالصبغة)','en_name'=>'CTA Angio Face(with contrast)']);
        $mri->radiology_types()->create(['ar_name'=>'فحص انجيو على المخ','en_name'=>'CTA Angio Brain']);
        $mri->radiology_types()->create(['ar_name'=>'فحص انجيو على شرايين الرقبة','en_name'=>'CTA Angio carotid']);
        $mri->radiology_types()->create(['ar_name'=>'فحص انجيو على المخ و شرايين الرقبة','en_name'=>'CTA Angio Brain and carotid']);
        $mri->radiology_types()->create(['ar_name'=>'فحص انجيو على الاورطى البطنى و الصدرى','en_name'=>'CTA Angio Aorta Chest & Abdomen']);
        $mri->radiology_types()->create(['ar_name'=>'فحص انجيو على الاورطى و الاطراف السفلية','en_name'=>'CTA Angio Aorta Chest & Abdomen & Both Lower Limbs']);
        $mri->radiology_types()->create(['ar_name'=>'فحص انجيو على الاورطى و طرف علوى فقط ','en_name'=>'CTA Angio Aorta Chest & Abdomen & one upper Limb']);
        $mri->radiology_types()->create(['ar_name'=>'فحص انجيو على اوردة الاطراف السفلية','en_name'=>'CTA Angio Venogram Both Lower Limbs']);
        $mri->radiology_types()->create(['ar_name'=>'فحص انجيو على شرايين القلب','en_name'=>'CTA angio Coronary']);
        $mri->radiology_types()->create(['ar_name'=>'الشعب الهوائية بدون استخدام منظار','en_name'=>'CTA Virtual Bronchoscopy']);
        $mri->radiology_types()->create(['ar_name'=>'الشريان الرئوى ','en_name'=>'CTA Pulmonary']);
        $mri->radiology_types()->create(['ar_name'=>'فحص انجيو على شرايين الكلى','en_name'=>'CTA Renal']);
        $mri->radiology_types()->create(['ar_name'=>'فحص محدود + عينة','en_name'=>'Limited CT Study + biopsy']);
        $mri->radiology_types()->create(['ar_name'=>'عينة محدودة عن طريق الموجات الصوتية','en_name'=>'Biopsy Under US']);
        $mri->radiology_types()->create(['ar_name'=>'عينة من الغدة الدرقية','en_name'=>'Thyroid Biopsy Under US']);
        $mri->radiology_types()->create(['ar_name'=>'عينة محدودة من العظم','en_name'=>'Bone Biopsy']);
        $mri->radiology_types()->create(['ar_name'=>' ','en_name'=>'Biopsy with big tale']);
        $mri->radiology_types()->create(['ar_name'=>'عينة من الصدر عن طريق الأنبوب','en_name'=>'Chest Tube Biopsy']);
        $mri->radiology_types()->create(['ar_name'=>'تفريغ تجمع ','en_name'=>'Drinage']);
        $mri->radiology_types()->create(['ar_name'=>'الوزن ( 100 كجم واقل من 110 كجم )','en_name'=>'Over wight from 100to 110']);
        $mri->radiology_types()->create(['ar_name'=>'الوزن ( 110 كجم واقل من 120 كجم )','en_name'=>'Over wight from 110to 120']);
        $mri->radiology_types()->create(['ar_name'=>'الوزن ( 120 كجم واقل من 130 كجم )','en_name'=>'Over wight from 120to 130']);
        $mri->radiology_types()->create(['ar_name'=>'الوزن ( 130 كجم واقل من 140 كجم )','en_name'=>'Over wight from 130to 140']);
        $mri->radiology_types()->create(['ar_name'=>'الوزن ( 140 كجم واقل من 150 كجم )','en_name'=>'Over wight from 140to 150']);
        //////////////////////////////////////////////////////////////////////////////////////////
        $mri = RadiologyTypeCategory::create(['ar_name'=>'اﻷشعة العادية - أشعة أكس','en_name'=>'X-Ray']);
        $mri->radiology_types()->create(['ar_name'=>'عظام الجمجمة وضعين','en_name'=>'Skull ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'النتوء الحلمى الأيمن والأيسر','en_name'=>'Mastoids ( Both Sides )']);
        $mri->radiology_types()->create(['ar_name'=>'الجيوب الأنفية وضعين','en_name'=>'Paranasal Sinuses ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'مفصلى الفك جانبين','en_name'=>'T.M.J. Bilateral']);
        $mri->radiology_types()->create(['ar_name'=>'البلعوم الأنفى','en_name'=>'Nasopharynx ( 1 View )']);
        $mri->radiology_types()->create(['ar_name'=>'فقرات عنقية أربع أوضاع','en_name'=>'Cervical Spine ( 4 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'فقرات عنقية  وضعين','en_name'=>'Cervical Spine ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'فقرات قطنية وضعين','en_name'=>'Lumbar Spine ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'فقرات قطنية  أربع أوضاع','en_name'=>'Lumbar Spine ( 4 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'وضع اضافى على فقرة قطنية او ظهرية','en_name'=>'Lumbar Spine Extra View']);
        $mri->radiology_types()->create(['ar_name'=>'فقرات ظهرية','en_name'=>'Dorsal Spine']);
        $mri->radiology_types()->create(['ar_name'=>'مفصل الكتف','en_name'=>'Shoulder']);
        $mri->radiology_types()->create(['ar_name'=>'مفصل الكوع - وضعين','en_name'=>'Elbow Joint ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'مفصل الرسغ - وضعين','en_name'=>'Wrist Joint ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'العضد أو الساعد - وضعين','en_name'=>'Forearm or Arm ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'اليد - وضعين','en_name'=>'Hand ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'وضع اضافى ','en_name'=>'Additional  View']);
        $mri->radiology_types()->create(['ar_name'=>'الحوض - وضع واحد','en_name'=>'Pelvis ( 1 View )']);
        $mri->radiology_types()->create(['ar_name'=>'مفصل الفخذ - وضعين','en_name'=>'Hip Joint ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'عظام الفخذ - وضعين','en_name'=>'Femur ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'مفصل الركبة - وضعين','en_name'=>'Knee Joint ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'عظام الساق - وضعين','en_name'=>'Leg ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'مفصل الكاحل - وضعين','en_name'=>'Ankle Joint ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'عظام القدم - وضعين','en_name'=>'Foot ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'الكعبين','en_name'=>'Both Heels']);
        $mri->radiology_types()->create(['ar_name'=>'وضع اضافى','en_name'=>'Additional View']);
        $mri->radiology_types()->create(['ar_name'=>'الصدر والقلب وضع واحد','en_name'=>'Chest & Heart ( 1 View )']);
        $mri->radiology_types()->create(['ar_name'=>'الصدر والقلب وضعين','en_name'=>'Chest & Heart ( 2 Views )']);
        $mri->radiology_types()->create(['ar_name'=>'بلعوم أو مرئ بالباريوم','en_name'=>'Hypopharynx, Esophagus ( Swallow )']);
        $mri->radiology_types()->create(['ar_name'=>'أسفل المرئ والمعدة والاثنى عشر','en_name'=>'Barium meal']);
        $mri->radiology_types()->create(['ar_name'=>'القولون بالباريوم','en_name'=>'Barium Enema']);
        $mri->radiology_types()->create(['ar_name'=>'مسالك بولية عادية','en_name'=>'U.T.']);
        $mri->radiology_types()->create(['ar_name'=>'مسالك بولية بالصبغة','en_name'=>'Intravenous Urography ( IVU )']);
        $mri->radiology_types()->create(['ar_name'=>'قناة مجرى البول -  بالصبغة','en_name'=>'Ascending Uretherography']);
        $mri->radiology_types()->create(['ar_name'=>'المثانة وقناة مجرى البول','en_name'=>'Cysto - Uretherography']);
        $mri->radiology_types()->create(['ar_name'=>'أشعة بالصبغة على الناصور','en_name'=>'Sinogram']);
        $mri->radiology_types()->create(['ar_name'=>'اشعة بالصبغة على الرحم ( طبيبةأ&طبيب أشعة )','en_name'=>'Hystro-salpingography ( HSG ) (Radiology doctor )']);
        //////////////////////////////////////////////////////////////////////////////////////////
        $mri = RadiologyTypeCategory::create(['ar_name'=>'الموجات فوق الصوتية','en_name'=>'Ultra Sound']);
        $mri->radiology_types()->create(['ar_name'=>'البطن','en_name'=>'Abdomen']);
        $mri->radiology_types()->create(['ar_name'=>'الحوض','en_name'=>'Pelvis']);
        $mri->radiology_types()->create(['ar_name'=>'البطن والحوض','en_name'=>'Abdomen & Pelvis']);
        $mri->radiology_types()->create(['ar_name'=>'الغدة الدرقية','en_name'=>'Thyroid Gland']);
        $mri->radiology_types()->create(['ar_name'=>'الثدى','en_name'=>'Breast']);
        $mri->radiology_types()->create(['ar_name'=>'المفاصل (الركبة -الكوع -الرسغ ...)','en_name'=>'Joints']);
        $mri->radiology_types()->create(['ar_name'=>'متابعة تبويض','en_name'=>'Follicular.Scanning']);
        $mri->radiology_types()->create(['ar_name'=>'موجات صوتية عن طريق المهبل','en_name'=>'Trans Vaginal']);
        $mri->radiology_types()->create(['ar_name'=>'موجات صوتية عن طريق الشرج','en_name'=>'Trans Rictal']);
        $mri->radiology_types()->create(['ar_name'=>'عينة عن طريق الموجات الصوتية','en_name'=>'Biopsy Under US']);
        $mri->radiology_types()->create(['ar_name'=>'تفريغ تجمع بالصدر او البطن باستخدام الموجات الصوتية','en_name'=>'Drainage of thoracic or abdominal collection']);

        //////////////////////////////////////////////////////////////////////////////////////////
        $mri = RadiologyTypeCategory::create(['ar_name'=>'الموجات فوق الصوتية الملونة','en_name'=>'Doppler']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر وريد كبدى','en_name'=>'Portal Doppler']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر شرايين الرقبة','en_name'=>'Carotid Doppler']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر شرايين الكلى','en_name'=>'Renal Doppler']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر خصيتين و كيس الصفن','en_name'=>'Scrotal Doppler']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر حمل','en_name'=>'Obst Doppler']);
        $mri->radiology_types()->create(['ar_name'=>'رباعية الابعاد على الحمل ','en_name'=>'4D']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر اوردة طرف  واحد','en_name'=>'Venous Doppler for one L L']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر شرايين طرف  واحد','en_name'=>'Arterial Doppler for one L L']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر اوردة و شرايين طرف  واحد','en_name'=>'Arterial and Venous Doppler for one L L']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر اوردة طرفيين','en_name'=>'Venous Doppler for both L L']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر شرايين طرفيين ','en_name'=>'Arterial Doppler for Both L L']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر اوردة و شرايين طرفيين ','en_name'=>'Arterial and Venous Doppler for Both L L']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر العضو الذكرى','en_name'=>'Penile Doppler']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر على مفصل عظمى','en_name'=>'Joints & Limbs']);
        $mri->radiology_types()->create(['ar_name'=>'دوبلر على العضلات','en_name'=>'Muscles']);
        //////////////////////////////////////////////////////////////////////////////////////////
        $mri = RadiologyTypeCategory::create(['ar_name'=>'قياس كثافة العظام','en_name'=>'DEXA']);
        $mri->radiology_types()->create(['ar_name'=>'كامل الجسم','en_name'=>'Total Body Dexa']);
        //////////////////////////////////////////////////////////////////////////////////////////
        $mri = RadiologyTypeCategory::create(['ar_name'=>'الماموجرام','en_name'=>'Mamogram + US']);
        $mri->radiology_types()->create(['ar_name'=>'الثديين','en_name'=>'Both Breasts']);
        $mri->radiology_types()->create(['ar_name'=>'ثدى جانب واحد','en_name'=>'Breast (One Side)']);
        //////////////////////////////////////////////////////////////////////////////////////////
        $mri = RadiologyTypeCategory::create(['ar_name'=>'البانوراما','en_name'=>'Panorama']);
        $mri->radiology_types()->create(['ar_name'=>'بانوراما الاسنان الرقمى','en_name'=>'Digital Panorama']);
        $mri->radiology_types()->create(['ar_name'=>'سيفالومترى ','en_name'=>'Cephalometry']);

    }
}


